### ISSUE TITLE
SQL-Einschränkung erzeugt Fehler bei Falscher Syntax

### ISSUE THREAD

**Issue by Hauge** [MetaModels/attribute_select#23]
Version ist folgende (bei allen späteren nightlys ist kein login mehr möglich):
Contao 3.3.5
```
metamodels/core                                       dev-tng @ d2de92        2014-08-27 22:04:42
contao-community-alliance/dc-general                  dev-develop @ e8feea    2014-08-28 15:20:45
metamodels/attribute_select                           dev-tng @ 6ea48f        2014-08-14 02:16:24
```
Gibt man bei der SQL-Einschränkung die Tabelle nicht mit an, also so:
![select_2](https://cloud.githubusercontent.com/assets/1571133/4174640/b94559e4-359d-11e4-9f17-5a04cad87375.JPG)
Ergibt das sofort einen dicken Fehler:
```
Fatal error: Uncaught exception Exception with message Query error: Column 'pid' in where clause is ambiguous (SELECT COUNT(mm_zimmerkategorien.klassifizierung) as mm_count, mm_taxonomie_sub.* FROM mm_taxonomie_sub LEFT JOIN mm_zimmerkategorien ON (mm_zimmerkategorien.klassifizierung=mm_taxonomie_sub.id) WHERE (pid=30) GROUP BY mm_taxonomie_sub.id ORDER BY mm_taxonomie_sub.sorting) thrown in system/modules/core/library/Contao/Database/Statement.php on line 283

#0 system/modules/core/library/Contao/Database/Statement.php(254): Contao\Database\Statement->query()
#1 system/modules/metamodelsattribute_select/MetaModels/Attribute/Select/Select.php(267): Contao\Database\Statement->execute()
#2 system/modules/metamodelsattribute_select/MetaModels/Attribute/Select/Select.php(127): MetaModels\Attribute\Select\Select->getFilterOptions(NULL, false)
#3 system/modules/metamodels/MetaModels/BackendIntegration/InputScreen/InputScreen.php(150): MetaModels\Attribute\Select\Select->getFieldDefinition(Array)
#4 system/modules/metamodels/MetaModels/BackendIntegration/InputScreen/InputScreen.php(196): MetaModels\BackendIntegration\InputScreen\InputScreen->translateProperty(Array, Object(MetaModels\MetaModel), 'klassifizierung')
#5 system/modules/metamodels/MetaModels/BackendIntegration/InputScreen/InputScreen.php(76): MetaModels\BackendIntegration\InputScreen\InputScreen->translateRows(Array)
#6 system/modules/metamodels/MetaModels/BackendIntegration/ViewCombinations.php(262): MetaModels\BackendIntegration\InputScreen\InputScreen->__construct(Array, Array, Array)
#7 system/modules/metamodels/MetaModels/BackendIntegration/ViewCombinations.php(344): MetaModels\BackendIntegration\ViewCombinations::fetchInputScreenDetails()
#8 system/modules/metamodels/MetaModels/BackendIntegration/ViewCombinations.php(420): MetaModels\BackendIntegration\ViewCombinations::bufferModels()
#9 system/modules/metamodels/MetaModels/Dca/MetaModelDcaBuilder.php(325): MetaModels\BackendIntegration\ViewCombinations::getStandaloneInputScreens()
#10 system/modules/metamodels/MetaModels/BackendIntegration/Boot.php(177): MetaModels\Dca\MetaModelDcaBuilder->injectBackendMenu()
#11 system/initialize.php(244): MetaModels\BackendIntegration\Boot::perform()
#12 contao/main.php(24): require('/var/www/client...')
#13 {main}
```
das Problem -> kein Login mehr möglich im BE.
Man kann das lediglich über die DB lösen.
Mit der korrekten Syntax also so:
![select_3](https://cloud.githubusercontent.com/assets/1571133/4174646/3386d61a-359e-11e4-81bd-4c6ce76bccfa.JPG)
klappt das

**Comment by discordier** [comment]
Das Problem sollte behoben sein. MetaModels bricht das booten nun ab wenn eine Exception kommt.

**Comment by Hauge** [comment]
jop, passt
