### ISSUE TITLE
Fehlermeldung wenn Select-Feld = Filterbar

### ISSUE THREAD

**Issue by andre5tz** [MetaModels/attribute_select#26]
Hallo,
nach einem Update über Composer erhalte ich in MetaModels die aufgeführte Fehlermeldung.
Die Fehlermeldung scheint zu kommen, wenn ich in der Eingabemaske für die BE Erfassung ein Select-Feld auf Filterbar stelle. Wenn ich jetzt mein MetaModel aufrufe kommt die Meldung.
Nehme ich die Auswahl Filterbar raus, kommt auch keine Fehlermeldung mehr, nur fehlt dann natürlich der Filter.

```
Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM mm_xxx WHERE mm_xxx IN ('xxx')' at line 1 (SELECT FROM mm_xxx WHERE mm_xxx IN ('xxx')) thrown in system/modules/core/library/Contao/Database/Statement.php on line 283

 #0 system/modules/core/library/Contao/Database/Statement.php(254): Contao\Database\Statement->query()
 #1 [internal function]: Contao\Database\Statement->execute(Array)
 #2 system/modules/core/library/Contao/Database/Statement.php(502): call_user_func_array(Array, Array)
 #3 composer/vendor/metamodels/attribute_select/src/MetaModels/Filter/Rules/FilterRuleSelect.php(74): Contao\Database\Statement->executeUncached(Array)
 #4 composer/vendor/metamodels/attribute_select/src/MetaModels/Filter/Rules/FilterRuleSelect.php(88): MetaModels\Filter\Rules\FilterRuleSelect->sanitizeValue()
 #5 composer/vendor/metamodels/attribute_select/src/MetaModels/Attribute/Select/AbstractSelect.php(163): MetaModels\Filter\Rules\FilterRuleSelect->getMatchingIds()
 #6 composer/vendor/metamodels/core/src/MetaModels/Filter/Rules/SearchAttribute.php(81): MetaModels\Attribute\Select\AbstractSelect->searchFor('111 Zentrale Di...')
 #7 composer/vendor/metamodels/core/src/MetaModels/Filter/Filter.php(114): MetaModels\Filter\Rules\SearchAttribute->getMatchingIds()
 #8 composer/vendor/metamodels/core/src/MetaModels/Filter/Rules/Condition/ConditionAnd.php(59): MetaModels\Filter\Filter->getMatchingIds()
 #9 composer/vendor/metamodels/core/src/MetaModels/Filter/Filter.php(114): MetaModels\Filter\Rules\Condition\ConditionAnd->getMatchingIds()
 #10 composer/vendor/metamodels/core/src/MetaModels/Filter/Rules/Condition/ /ConditionAnd.php(59): MetaModels\Filter\Filter->getMatchingIds()
 #11 composer/vendor/metamodels/core/src/MetaModels/Filter/Filter.php(114): MetaModels\Filter\Rules\Condition\ConditionAnd->getMatchingIds()
 #12 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(197): MetaModels\Filter\Filter->getMatchingIds()
 #13 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(561): MetaModels\MetaModel->getMatchingIds(Object(MetaModels\Filter\Filter))
 #14 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(616): MetaModels\MetaModel->getIdsFromFilter(Object(MetaModels\Filter\Filter), 'sorting', NULL, NULL, 'ASC')
 #15 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Panel/DefaultLimitElement.php(74): MetaModels\DcGeneral\Data\Driver->fetchAll(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig))
 #16 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Panel/DefaultLimitElement.php(142): ContaoCommunityAlliance\DcGeneral\Panel\DefaultLimitElement->calculateTotal()
 #17 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Panel/DefaultPanel.php(92): ContaoCommunityAlliance\DcGeneral\Panel\DefaultLimitElement->initialize(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig), NULL)
 #18 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Panel/DefaultPanelContainer.php(85): ContaoCommunityAlliance\DcGeneral\Panel\DefaultPanel->initialize(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig), NULL)
 #19 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php(50): ContaoCommunityAlliance\DcGeneral\Panel\DefaultPanelContainer->initialize(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig))
 #20 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php(302): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->loadCollection()
 #21 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->showAll()
 #22 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(155): call_user_func_array(Array, Array)
 #23 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
 #24 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
 #25 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
 #26 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(119): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
 #27 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(129): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
 #28 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(238): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
 #29 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(263): MetaModels\BackendIntegration\Module->runDC()
 #30 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(283): MetaModels\BackendIntegration\Module->performNormal()
 #31 system/modules/core/classes/Backend.php(271): MetaModels\BackendIntegration\Module->generate()
 #32 contao/main.php(142): Contao\Backend->getBackendModule('metamodel_mm_gv...')
 #33 contao/main.php(293): Main->run()
 #34 {main}
```

 <blockquote>Contao 3.2.14 LTS
 Composer 2.2.3
 MetaModels dev-tng (25d17e7b) 2.0.x-dev
 metamodels/bundle_all 1.0.1
 contao-community-alliance/dc-general dev-develop (869cf5fd) 2.0.x-dev
</blockquote>

VG
André

**Comment by discordier** [comment]
Has been fixed.
