### ISSUE TITLE
Fehlermeldung beim Speichern von Datensätzen

### ISSUE THREAD

**Issue by kein-nickname** [MetaModels/attribute_select#28]
Version: Contao 3.3.4 und neuste TNG + neustes DC

Ich erhalte mit der neusten Version beim abspeichern folgende Meldung...
ein abspeichern ist nicht möglich!!!

```
Fatal error: Uncaught exception RuntimeException with message Invalid values encountered, itemId: NULL value: NULL thrown in composer/vendor/metamodels/attribute_select/src/MetaModels/Attribute/Select/MetaModelSelect.php on line 426

#0 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(754): MetaModels\Attribute\Select\MetaModelSelect->setDataFor(Array)
#1 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(843): MetaModels\MetaModel->saveAttribute(Object(MetaModels\Attribute\Select\MetaModelSelect), Array, NULL, NULL)
#2 composer/vendor/metamodels/core/src/MetaModels/Item.php(304): MetaModels\MetaModel->saveItem(Object(MetaModels\Item))
#3 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(776): MetaModels\Item->save()
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(613): MetaModels\DcGeneral\Data\Driver->save(Object(MetaModels\DcGeneral\Data\Model))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(670): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(1304): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(1277): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
#8 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit()
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(155): call_user_func_array(Array, Array)
#10 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#13 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(119): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(129): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(238): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#16 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(263): MetaModels\BackendIntegration\Module->runDC()
#17 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(283): MetaModels\BackendIntegration\Module->performNormal()
#18 system/modules/SWBackend/classes/Backend.php(151): MetaModels\BackendIntegration\Module->generate()
#19 contao/main.php(142): Backend->getBackendModule('metamodel_mm_ve...')
#20 contao/main.php(293): Main->run()
#21 {main}
```

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@kein-nickname could you please have a final look at this and tell if your issue has been resolved?

**Comment by lucdesign** [comment]
Fatal error: Uncaught exception RuntimeException with message Could not retrieve attribute 30 from MetaModel mm_projects. thrown in composer/vendor/metamodels/core/src/MetaModels/Events/DefaultPropertyConditionCreator.php on line 55
nach Löschen eines Attribut, das als Bedingung zur Sichtbarkeit eines Eingabefeldes benutzt wurde. Backend ist derzeit unerreichbar.

**Comment by lucdesign** [comment]
Hab die conditions aus der SQL-DB manuell gelöscht und das Backend geht wieder. Hoffentlich gibts keine side effects.

**Comment by discordier** [comment]
@lucdesign Das Problem laesst sich nun aber nicht mehr reproduzieren, oder?
Schuld war nun nur noch die fehlerhaft angelegte condition, oder?

Ansonsten brauchen wir hier einen reopen.

**Comment by lucdesign** [comment]
Ich würde das als Uncaught Error sehen. Natürlich habe ich den conditions das Attribut unterm Hintern weggezogen, aber dass dadurch gleich das ganze BE abkratzt, finde ich doch heavy. Ohne PHPmyAdmin plus ein Stück MM-Backendwissen plus PHP-Erfahrung hast du keine Chance. Ich bin Informatiker, aber das ist nicht jeder. Bessere Fehlerbehandlung täte not.

**Comment by discordier** [comment]
In der Tat, solche Dinge haben wir noch an ein paar Stellen, das moechte ich dann aber gerne auf 2.1 verschieben, da es "nur" ein usability bug ist.

**Comment by xantippe** [comment]
das ursprüngliche Problem des Tickets sollte gelöst sein - zumindest kann ich bei meinem Test mit MM 2.0.0alpha9 keinen Fehler feststellen - auch mit leerem Selectfeld

zum Thema Attribut gelöscht, was in Condition verwendet, gibt es ein Ticket: https://github.com/MetaModels/core/issues/640

dieses Ticket kann m.E. gelöscht werden...
