### ISSUE TITLE
Select Feld und Mehrsprachigkeit

### ISSUE THREAD

**Issue by Fr3d83** [MetaModels/attribute_select#43]
Hi,

ich wollte soetwas ähnlich nachbauen wie hier:
http://de.contaowiki.org/MetaModels_Beispiel:_%C3%9Cbersetzter_select

Soweit so gut, ich habe beide MMs in drei Sprachen angelegt + eine fallback Sprache.

"MM 1" ist zur eintragung von Kunden und "MM 2" ist eine Auflistung von Regionen.
"MM 2" hat einen Datensatz wo alle drei sprachen ausgefüllt sind. Nun habe ich "MM 2" in "MM 1" mittels eines übersetzungs select Attributs eingefügt.
![19-06-_2015_14-55-00](https://cloud.githubusercontent.com/assets/6480582/8301775/5acab05c-1991-11e5-8496-5356068e15b1.jpg)

Mir ist nur nicht so ganz klar was bei "select_langcolumn" stehen muss?

Wenn ich jetzt einen Datensatz in "MM 1" erstellen möchte, bekomme ich folgende Fehlermeldung:
```
[19-Jun-2015 12:43:15 GMT] PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: Unknown column 'region' in 'where clause' (SELECT mm_region.* FROM mm_region WHERE id=NULL AND region='de')' thrown in /wwwroot.wwwnew/system/modules/core/library/Contao/Database/Statement.php on line 279
#0 /wwwroot.wwwnew/system/modules/core/library/Contao/Database/Statement.php(250): Contao\Database\Statement->query()
#1 /wwwroot.wwwnew/system/modules/metamodelsattribute_translatedselect/classes/src/MetaModels/Attribute/TranslatedSelect/TranslatedSelect.php(144): Contao\Database\Statement->execute(NULL, 'de')
#2 /wwwroot.wwwnew/system/modules/metamodels/classes/src/MetaModels/DcGeneral/Data/Model.php(114): MetaModels\Attribute\TranslatedSelect\TranslatedSelect->valueToWidget(NULL)
#3 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php(479): MetaModels\DcGeneral\Data\Model->getProperty('region')
#4 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php(700): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->getWidget('region', NULL)
#5 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(429): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->renderWidget('region', false, NULL)
#6 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(674): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->buildFieldSet(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager), Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\Palette), NULL)
#7 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(780): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#8 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(755): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#10 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(141): call_user_func_array(Array, Array)
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 /wwwroot.wwwnew/system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 /wwwroot.wwwnew/system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(121): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 /wwwroot.wwwnew/system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#16 /wwwroot.wwwnew/system/modules/core/classes/Backend.php(262): MetaModels\BackendIntegration\Module->generate()
#17 /wwwroot.wwwnew/contao/main.php(137): Contao\Backend->getBackendModule('metamodel_mm_pa...')
#18 /wwwroot.wwwnew/contao/main.php(288): Main->run()
```
Nehme ich nun ein normales select Feld springt das select Feld immer wieder zurück zum ersten Wert wenn ich den Datensatz speichere, jedoch im FE wird der richtige Wert ausgegeben.
Meine Felder:
![22-06-_2015_11-52-30](https://cloud.githubusercontent.com/assets/6480582/8301828/ca71cf12-1991-11e5-9f05-7cf246dc8398.jpg)
![22-06-_2015_11-50-11](https://cloud.githubusercontent.com/assets/6480582/8301831/ca763cb4-1991-11e5-9b34-815aa6d6907c.jpg)
![22-06-_2015_11-49-54](https://cloud.githubusercontent.com/assets/6480582/8301830/ca75cb26-1991-11e5-898a-fe1e2ed80816.jpg)
![22-06-_2015_09-36-11](https://cloud.githubusercontent.com/assets/6480582/8301829/ca73e810-1991-11e5-9ac0-17936ff266e7.jpg)

Komisch ist, wenn ich eine Mehrfachauswahl mache, bleiben die richtigen werte im BE gechecked. 

Mein System:
- Contao Version - 3.2.19
- MM Version - 22.06.
- PHP Version - 5.6.7
- In der error.log steht nichts 

Hier im Forum entstanden:
https://community.contao.org/de/showthread.php?57701-Mehrsprachigkeit-von-select&p=374319#post374319

**Comment by discordier** [comment]
In deinem Falle brauchst du hier kein translated select sondern kannst das normale select verwenden. Das handelt die Ybersetzung fyr dich schon automatisch ab.

Das translated select ist fyr Faelle, wo du eine separate Sprachspalte in der Tabelle hast.

**Comment by discordier** [comment]
Es ist jedoch ein Problem, dass die `lang_column` hier Attribute bereit stellt obwohl das Attribut diese noch nicht versteht.

**Comment by xantippe** [comment]
besteht das Problem immer noch? wen ja, ein Ticket bei translated_select öffenen?

**Comment by zonky2** [comment]
Da seit Juni 2015 die Mehrsprachigkeit von Selects umgebaut wurde, es keinen Test/Rückmeldung von @Fr3d83 gab und keine vergleichbaren Fehlermeldungen zu finden sind, schließe ich das Ticket.
