### ISSUE TITLE
Fehlermeldung bei Speicherung bei Popup-Picker

### ISSUE THREAD

**Issue by xantippe** [MetaModels/attribute_select#50]
MM 2.0.0-alpha10, DCG 2.0.0-beta34

bei Umschaltung von Select oder Radiobutton auf Popup-Picker werden die vorhergehenden Werte nicht angezeigt

Bei Neuauswahl + Speichern kommt z.B. ```Property abteilung (select) did not accept the value (The values differ. Found '' expected 'gf').```

![shot105](https://cloud.githubusercontent.com/assets/1045318/13123600/36070142-d5bd-11e5-82eb-25781d305816.jpg)

**Comment by xantippe** [comment]
kann es sein, dass das mit https://github.com/MetaModels/core/issues/954#issuecomment-182632488 zusammen hängt?

**Comment by discordier** [comment]
Please try by changing this line:
https://github.com/MetaModels/attribute_select/blob/aa53353e1b6d8e0451d974b219cb3712d76259a0/src/MetaModels/Attribute/Select/AbstractSelect.php#L184
```diff
-$arrFieldDef['eval']['idProperty'] = $this->getAliasColumn();
+$arrFieldDef['eval']['idProperty'] = $this->getIdColumn();
```

**Comment by xantippe** [comment]
habe die hotfix-alpha11 eingespielt - bei der ist doch die Zeile schon auf ```$this->getIdColumn();``` umgestellt?!?

stelle ich von Select auf Popup um, und öffne den Picker kommt
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Invalid condition, not in hierarchical mode! thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php on line 209

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(1125): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->searchParentOf(Object(MetaModels\DcGeneral\Data\Model))
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(1146): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->parentsOf(Object(MetaModels\DcGeneral\Data\Model), Array)
#2 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(304): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->determineParentsOfValues()
#3 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(705): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->getTreeNodeStates()
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(728): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->determineModelState(Object(MetaModels\DcGeneral\Data\Model), 0)
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(831): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->treeWalkModel(Object(MetaModels\DcGeneral\Data\Model), 1, Array)
#6 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(870): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->getTreeCollectionRecursive(0, 0, NULL)
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(608): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->loadCollection(0)
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect.php(147): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->generatePopup()
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\dc-general\backend\generaltree.php(40): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect->run()
#10 {main}
```
das liegt aber offensichtlich daran, dass der Picker mit dem gespeicherten Wert nix anfangen kann - stelle ich zurück auf Select und wähle "nichts" + speichern und stelle dann wieder auf Picker um, kann ich den öffnen + wählen + speichern

bei erneutem öffnen des Pickers kommt
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Invalid condition, not in hierarchical mode! thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php on line 209

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(1125): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->searchParentOf(Object(MetaModels\DcGeneral\Data\Model))
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(1146): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->parentsOf(Object(MetaModels\DcGeneral\Data\Model), Array)
#2 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(304): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->determineParentsOfValues()
#3 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(705): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->getTreeNodeStates()
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(728): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->determineModelState(Object(MetaModels\DcGeneral\Data\Model), 0)
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(831): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->treeWalkModel(Object(MetaModels\DcGeneral\Data\Model), 1, Array)
#6 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(870): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->getTreeCollectionRecursive(0, 0, NULL)
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(608): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->loadCollection(0)
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect.php(147): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->generatePopup()
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\dc-general\backend\generaltree.php(40): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect->run()
#10 {main}
```
nach erneutem Umschalten->Select->Picker bleibt die Meldung im Picker "...Invalid condition, not in hierarchical mode! "

Ein Feld mit Ansichtsbedingung (Subpalette) auf einen der vorhanden Select-Werte wird bei keiner der getesteten Varianten angezeigt

:-(

**Comment by xantippe** [comment]
siehe auch https://github.com/MetaModels/core/issues/651#issuecomment-186110711

**Comment by discordier** [comment]
See https://github.com/contao-community-alliance/dc-general/commit/d169f0dbcf4ccef8cc6c6ea643b5282a1bc3f3f2

**Comment by xantippe** [comment]
Popup-Picker funktioniert damit...
